name: Tauri Release Updater CI

on: workflow_dispatch

jobs:
  release-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Yarn install
        run: yarn install

      - name: Release updater file
        run: yarn updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
